name: Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.6"

      - name: Build
        run: go build -o repositorio-backend-WS -v ./

      - name: Create Windows Service
        run: |
          sc delete repositorio-backend-WS || true
          sc create repositorio-backend-WS binPath= "$PWD/repositorio-backend-WS.exe" start= auto

